### PR TITLE
Update strings.xml of main values

### PR DESCRIPTION
**Pull request by TacoTheDank**
Many English and grammatical corrections (pls don't just close the pull request if you find changes you don't like; just tell me instead and I'll change it to what you say, thanks)

### CODE REVIEW

**Comment by TacoTheDank** [comment]
yay :3

**Comment by calvinnor** [comment]
@TacoTheDank Thanks for your contribution!
It's nice to have more eyes on the project :wink:

**Comment by TacoTheDank** [comment]
yea lol i like this app

**Comment by abdulmalikkhan655** [comment]
becare full guyz @TacoTheDank  is a scammer  so becareful

**Comment by TacoTheDank** [comment]
KEK @abdulmalikkhan655 gtfo of here dude you must be really insecure to try to slander my name that much after exposing your bullshit

**Comment by abdulmalikkhan655** [comment]
scammer

**Comment by TacoTheDank** [comment]
oh no thats only the 40th time youve called me that, its really starting to get to me now

😒

**Pull request merged**
