### PR TITLE
Add an option to disable animations

### LINKED ISSUE #250: Option to disable animations
I own an older, less powerful device and would love an option to disable animations.

### PR DESCRIPTION
**Pull request by carusooo**
This adds a preference to disable animations. The setting is not localized.
Closes #250

When animations are disabled
* Uses default animation for recycler views in the AlbumsFragment and
  RvMediaFragment
* Uses the default animation for the PagerView in SingleMediaActivity
* Uses a fade animation for the toolbar when transitioning in and out of
  fullscreen in SingleMediaActivity

### CODE REVIEW

**Comment by carusooo** [comment]
Tested on Pixel XL 2 running 8.1.0

**Comment by dnldsht** [comment]
@macarus0  I think who use this feature has a not performant phone, and want all the animations disabled, also the animation on the toolbar, don't you think so?

**Comment by carusooo** [comment]
I left the toolbar animations since I was seeing a brief white flash when calling hide() on the toolbar directly.  I am working through trying to trace the performance impact with systrace, I can update on the comparison. 

Do you prefer the white flash and no animation or the animation?

**Comment by dnldsht** [comment]
@macarus0 I prefer the animation :)

**Comment by carusooo** [comment]
I didn't see any difference with systrace (although I am far from an expert), so I think it's safe to always use the animation in the fullscreen/non-fullscreen case.

**Pull request merged**
