### PR TITLE
Rotate based on exif

### PR DESCRIPTION
**Pull request by dethstar**
This fixes https://github.com/HoraApps/LeafPic/issues/118 or at least most cases.

Exif is tricky and some phones even take pictures mirrored and you're supposed to flip them horizontally/vertically based on the exif value. 
[Here's](http://sylvana.net/jpegcrop/exif_orientation.html) a good reference about this issue.

Also, I added the function on the bitmaputils class but it doesn't ever use a bitmap so I'm sorry please let me know if I should move it somewher eelse😃

### CODE REVIEW

**Comment by dnldsht** [comment]
@dethstar I think the approach is right since the orientation on the Content Provider is not always right, but I think is better if we use the `SupportExifInterface`.

[Here](https://android-developers.googleblog.com/2016/12/introducing-the-exifinterface-support-library.html) you can find the resource.
Anyway thanks for the contribution :)

**Comment by dethstar** [comment]
ExifInterface is what I'm using to get the actual rotation though. Are you saying to use it instead of  SubsamplingScaleImageView ?

**Comment by dnldsht** [comment]
I'm talking for the `ExifInterface` from the support library, that doesn't work with paths but with `Streams` so we can use Uris instead of the path(since it isn't always available)

you have to include this dependency
```
compile "com.android.support:exifinterface:$supportVersion"
```

an use like this:
```java
Uri uri; // the URI you've received from the other app
InputStream in;
try {
  in = getContentResolver().openInputStream(uri);
  ExifInterface exifInterface = new ExifInterface(in);
  // Now you can extract any Exif tag you want
  // Assuming the image is a JPEG or supported raw format
} catch (IOException e) {
  // Handle any errors
} finally {
  if (in != null) {
    try {
      in.close();
    } catch (IOException ignored) {}
  }
}
```

**Comment by dethstar** [comment]
There you go :)

**Pull request merged**
