### PR TITLE
Mx Player Issue resolved.

### PR DESCRIPTION
**Pull request by abhimaniCodal**

### CODE REVIEW

**Comment by dnldsht** [comment]
Is it different from this?
```java
Intent intent = new Intent(Intent.ACTION_VIEW).setDataAndType(uri, video.getMimeType());
intent.setFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
startActivity(intent);
```

**Comment by abhimaniCodal** [comment]
Yes I manually grant uri permission for all activities which can play video. It is working in Mx Player now.

**Comment by abhimaniCodal** [comment]
I added following code

```
for (ResolveInfo resolveInfo : resInfoList) {
 				String packageName = resolveInfo.activityInfo.packageName;
 				getContext().grantUriPermission(packageName, uri,
 						Intent.FLAG_GRANT_WRITE_URI_PERMISSION | Intent
 								.FLAG_GRANT_READ_URI_PERMISSION);
 			}
```

**Comment by dnldsht** [comment]
Is the write permission necessary?

**Comment by abhimaniCodal** [comment]
Okay I have removed write permission. Thanks for correcting me

**Comment by dnldsht** [comment]
I tested MX player with the following code and it works
```java
Intent intent = new Intent(Intent.ACTION_VIEW).setDataAndType(uri, video.getMimeType());
intent.setFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
startActivity(intent);
```
I think this way you give permission only to that given Uri, but I may be wrong! 

close #440

**Comment by abhimaniCodal** [comment]
Hey this is nice and clean solution. Rather than mine. Thanks man.

**Pull request merged**
