### PR TITLE
Canceling selection resets the toolbar (with either "back-hardware-bu…

### PR DESCRIPTION
**Pull request by akorb**
…tton" or "check-software-button")

I have already an idea for a more elegant solution but this might involve a bit more code changes. And I think the first commit to a project shouldn't be such a huge change :)

### CODE REVIEW

**Comment by dnldsht** [comment]
@akorb did you understand why sometimes the toolbar icons don't get updated?
related issues #500  #492

**Comment by akorb** [comment]
I tried to reproduce both issues (without using my commit) but I didn't succeed. #500 is exactly the other way round than what my commit fixed.

**Comment by dnldsht** [comment]
I'm using oreo 8.1 and this happens to me all the time, I don't know if is a rom bug or what will try this on other devices

**Comment by akorb** [comment]
Sounds like the nightmare of every dev. Difficult to reproduce and version-specific.

I'm on Oreo 8.0.0 with OxygenOS. If this helps. Did you try the Android Emulator?

**Comment by dnldsht** [comment]
Fix and clean up on #527

**Pull request closed without merging**
