### PR TITLE
Added Crashlytics for bug reporting

### PR DESCRIPTION
**Pull request by sankarganeshsiva**

### CODE REVIEW

**Comment by licaon-kter** [comment]
Hope these libs can be easy to disable for the F-Droid build.

**Comment by sankarganeshsiva** [comment]
Ya it can be easily disabled.

**Comment by dnldsht** [comment]
I took a look at the service, it is nice! but there is a very similar service provided by google that report me crashes and give me a look at the active users. 
Does it make the app heavier/slower?  does it have any cool feature that google Developer console doesn't provide?

**Comment by sankarganeshsiva** [comment]
There is no “best” service here, there only the service that better suits our needs. Google developer console is very powerful with built in crash reporting. Having a competitor like Crashlytics, which used to be the best in class on its category. And crashlytics was used in indulstry all over the world.

**Comment by dnldsht** [comment]
@sankarganeshsiva  For the monent I only need crash report for app version (that is available on GDC) so I'm not gonna use Crashlytics.

**Comment by wyatt8740** [comment]
i see you closed this issue, but I'm glad you chose not to implement crashlytics as that would almost certainly be a flag on F-Droid.

**Pull request closed without merging**
