### PR TITLE
#503, fixed sharing images and videos is now possible

### PR DESCRIPTION
**Pull request by ShardulKoli**
#503 is fixed

### CODE REVIEW

**Comment by dnldsht** [comment]
did you miss something before push? it looks like a stub and it would not work on oreo...

**Comment by ShardulKoli** [comment]
I am using oreo, working fine for me the app was crashing instantly after the share button was clicked before I made this fix

**Comment by dnldsht** [comment]
why are you forcing those files? you are sharing `foo.jpg` and `video.mp4` no matter, what are those created by exoplayer?

**Comment by ShardulKoli** [comment]
It's just a sample string it picks the file you choose not the ones mentioned in the string, I have tried and tested it and it works or I wouldn't have submitted the pull request otherwise. I can send you a sceenrecording as well if you are not convinced.

**Comment by dnldsht** [comment]
Still getting crashes!
You can checkout [here](https://github.com/HoraApps/LeafPic/tree/lp-470-fix-share-oreo) how this shoul be fixed.
image

**Pull request closed without merging**
